		
Rem
bbdoc: 
End Rem

Module axe.Angle

ModuleInfo "Version: 0.01"
ModuleInfo "Author: Simon Armstrong"
ModuleInfo "License: Berkley"
ModuleInfo "Copyright: (C) 2014 Simon Armstrong"
ModuleInfo "Copyright: (C) 2002-2013 The ANGLE Project Authors."

ModuleInfo "CC_OPTS:-std=c++11"
ModuleInfo "CC_OPTS: -D_WIN32_WINNT=0x0500"

Strict

Import pub.freeprocess

?Win32

Import pub.Win32

Import "include/*.h"
Import "util/*.h"
Import "src/*.h"

Import "util/EGLWindow.cpp"
Import "util/OSWindow.cpp"
Import "util/shader_utils.cpp"
Import "util/win32/Win32Timer.cpp"
Import "util/win32/Win32Window.cpp"
Import "util/win32/Win32_path_utils.cpp"

Import "src/common/angleutils.cpp"
Import "src/common/blocklayout.cpp"
Import "src/common/debug.cpp"
Import "src/common/event_tracer.cpp"
Import "src/common/mathutil.cpp"
Import "src/common/RefCountObject.cpp"
Import "src/common/tls.cpp"
Import "src/common/utilities.cpp"

Import "src/libEGL/Config.cpp"
Import "src/libEGL/Display.cpp"
Import "src/libEGL/libEGL.cpp"
Import "src/libEGL/main.cpp"
Import "src/libEGL/Surface.cpp"

Import "src/libGLESv2/angletypes.cpp"
Import "src/libGLESv2/Buffer.cpp"
Import "src/libGLESv2/Caps.cpp"
Import "src/libGLESv2/Context.cpp"
Import "src/libGLESv2/Error.cpp"
Import "src/libGLESv2/Fence.cpp"
Import "src/libGLESv2/Float16ToFloat32.cpp"
'Import "src/libGLESv2/formatutils.cpp"
Import "src/libGLESv2/Framebuffer.cpp"
Import "src/libGLESv2/FramebufferAttachment.cpp"
Import "src/libGLESv2/HandleAllocator.cpp"
'Import "src/libGLESv2/libGLESv2.cpp"
Import "src/libGLESv2/main.cpp"
Import "src/libGLESv2/Program.cpp"
'Import "src/libGLESv2/ProgramBinary.cpp"
Import "src/libGLESv2/Query.cpp"
Import "src/libGLESv2/queryconversions.cpp"
Import "src/libGLESv2/Renderbuffer.cpp"
Import "src/libGLESv2/ResourceManager.cpp"
Import "src/libGLESv2/Sampler.cpp"
Import "src/libGLESv2/Shader.cpp"
Import "src/libGLESv2/State.cpp"
Import "src/libGLESv2/Texture.cpp"
Import "src/libGLESv2/TransformFeedback.cpp"
Import "src/libGLESv2/Uniform.cpp"
Import "src/libGLESv2/validationES.cpp"
Import "src/libGLESv2/validationES2.cpp"
Import "src/libGLESv2/validationES3.cpp"
Import "src/libGLESv2/VertexArray.cpp"
Import "src/libGLESv2/VertexAttribute.cpp"

'Import "src/libGLESv2/renderer/copyimage.cpp"
Import "src/libGLESv2/renderer/Image.cpp"
Import "src/libGLESv2/renderer/IndexRangeCache.cpp"
Import "src/libGLESv2/renderer/loadimage.cpp"
'Import "src/libGLESv2/renderer/loadimageSSE2.cpp"
'Import "src/libGLESv2/renderer/Renderer.cpp"
	
Rem	

Import "src/libGLESv2/renderer/d3d/d3dBufferD3D.cpp"
Import "src/libGLESv2/renderer/d3d/DynamicHLSL.cpp"
'Import "src/libGLESv2/renderer/d3d/HLSLCompiler.cpp"
Import "src/libGLESv2/renderer/d3d/ImageD3D.cpp"
Import "src/libGLESv2/renderer/d3d/IndexBuffer.cpp"
Import "src/libGLESv2/renderer/d3d/IndexDataManager.cpp"
Import "src/libGLESv2/renderer/d3d/MemoryBuffer.cpp"
Import "src/libGLESv2/renderer/d3d/ShaderD3D.cpp"
Import "src/libGLESv2/renderer/d3d/TextureD3D.cpp"
Import "src/libGLESv2/renderer/d3d/TextureStorage.cpp'
Import "src/libGLESv2/renderer/d3d/TransformFeedbackD3D.cpp"
Import "src/libGLESv2/renderer/d3d/VertexBuffer.cpp"
Import "src/libGLESv2/renderer/d3d/VertexDataManager.cpp"

Import "src/libGLESv2/renderer/d3d/d3d9/Blit9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/Buffer9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/Fence9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/formatutils9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/Image9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/IndexBuffer9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/Query9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/Renderer9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/renderer9_utils.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/RenderTarget9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/ShaderExecutable9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/SwapChain9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/TextureStorage9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/VertexBuffer9.cpp"
Import "src/libGLESv2/renderer/d3d/d3d9/VertexDeclarationCache.cpp"

Import "src/libGLESv2/renderer/d3d/d3d11/Blit11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Buffer11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Clear11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Fence11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/formatutils11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Image11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/IndexBuffer11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/InputLayoutCache.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/PixelTransfer11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Query11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/Renderer11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/renderer11_utils.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/RenderStateCache.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/RenderTarget11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/ShaderExecutable11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/SwapChain11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/TextureStorage11.cpp"
Import "src/libGLESv2/renderer/d3d/d3d11/VertexBuffer11.cpp"

EndRem

Import "src/compiler/preprocessor/DiagnosticsBase.cpp"
Import "src/compiler/preprocessor/DirectiveHandlerBase.cpp"
Import "src/compiler/preprocessor/DirectiveParser.cpp"
Import "src/compiler/preprocessor/ExpressionParser.cpp"
Import "src/compiler/preprocessor/Input.cpp"
Import "src/compiler/preprocessor/Lexer.cpp"
Import "src/compiler/preprocessor/Macro.cpp"
Import "src/compiler/preprocessor/MacroExpander.cpp"
Import "src/compiler/preprocessor/Preprocessor.cpp"
Import "src/compiler/preprocessor/Token.cpp"
Import "src/compiler/preprocessor/Tokenizer.cpp"


Import "src/compiler/translator/BuiltInFunctionEmulator.cpp"
Import "src/compiler/translator/CodeGen.cpp"
Import "src/compiler/translator/Compiler.cpp"
Import "src/compiler/translator/compilerdebug.cpp"
Import "src/compiler/translator/DetectCallDepth.cpp"
Import "src/compiler/translator/DetectDiscontinuity.cpp"
Import "src/compiler/translator/Diagnostics.cpp"
Import "src/compiler/translator/DirectiveHandler.cpp"
Import "src/compiler/translator/FlagStd140Structs.cpp"
Import "src/compiler/translator/ForLoopUnroll.cpp"
Import "src/compiler/translator/glslang_lex.cpp"
Import "src/compiler/translator/glslang_tab.cpp"
Import "src/compiler/translator/InfoSink.cpp"
Import "src/compiler/translator/Initialize.cpp"
Import "src/compiler/translator/InitializeDll.cpp"
Import "src/compiler/translator/InitializeParseContext.cpp"
Import "src/compiler/translator/InitializeVariables.cpp"
Import "src/compiler/translator/Intermediate.cpp"
Import "src/compiler/translator/IntermNode.cpp"
Import "src/compiler/translator/intermOut.cpp"
Import "src/compiler/translator/IntermTraverse.cpp"
Import "src/compiler/translator/LoopInfo.cpp"
Import "src/compiler/translator/OutputESSL.cpp"
Import "src/compiler/translator/OutputGLSL.cpp"
Import "src/compiler/translator/OutputGLSLBase.cpp"
Import "src/compiler/translator/OutputHLSL.cpp"
Import "src/compiler/translator/parseConst.cpp"
Import "src/compiler/translator/ParseContext.cpp"
Import "src/compiler/translator/PoolAlloc.cpp"
Import "src/compiler/translator/QualifierAlive.cpp"
Import "src/compiler/translator/RegenerateStructNames.cpp"
Import "src/compiler/translator/RemoveTree.cpp"
Import "src/compiler/translator/RewriteElseBlocks.cpp"
'Import "src/compiler/translator/ScalarizeVecAndMatConstructorArgsImporta.cpp"
Import "src/compiler/translator/SearchSymbol.cpp"
Import "src/compiler/translator/ShaderLang.cpp"
Import "src/compiler/translator/ShaderVars.cpp"
Import "src/compiler/translator/StructureHLSL.cpp"
Import "src/compiler/translator/SymbolTable.cpp"
Import "src/compiler/translator/TranslatorESSL.cpp"
Import "src/compiler/translator/TranslatorGLSL.cpp"
Import "src/compiler/translator/TranslatorHLSL.cpp"
Import "src/compiler/translator/Types.cpp"
Import "src/compiler/translator/UnfoldShortCircuit.cpp"
Import "src/compiler/translator/UnfoldShortCircuitAST.cpp"
Import "src/compiler/translator/UniformHLSL.cpp"
Import "src/compiler/translator/util.cpp"
Import "src/compiler/translator/UtilsHLSL.cpp"
Import "src/compiler/translator/ValidateLimitations.cpp"
Import "src/compiler/translator/ValidateOutputs.cpp"
Import "src/compiler/translator/VariableInfo.cpp"
Import "src/compiler/translator/VariablePacker.cpp"
Import "src/compiler/translator/VersionGLSL.cpp"

Import "src/compiler/translator/depgraph/DependencyGraph.cpp"
Import "src/compiler/translator/depgraph/DependencyGraphBuilder.cpp"
Import "src/compiler/translator/depgraph/DependencyGraphOutput.cpp"
Import "src/compiler/translator/depgraph/DependencyGraphTraverse.cpp"

Import "src/compiler/translator/timing/RestrictFragmentShaderTiming.cpp"
Import "src/compiler/translator/timing/RestrictVertexShaderTiming.cpp"


Extern "C"

End Extern
